In [ ]:
pip install patool

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: patool in /usr/local/lib/python3.10/dist-packages (1.12)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import shutil

# Copia el archivo desde el drive al entorno de ejecucion

shutil.copyfile("./drive/MyDrive/data/train.zip","./train.zip")

'./train.zip'

In [ ]:
import zipfile
with zipfile.ZipFile("./train.zip", 'r') as zip_ref:
    zip_ref.extractall("train")

In [ ]:
import pandas as pd
df = pd.read_csv("700tokensVal.csv", sep=";")
df["summary"]=df["1"]
df["article"]=df["0"]

In [ ]:
df

,Unnamed: 0,0,1,summary,article
0,0,"El Urbia Palma disputa hoy, a las 20:00 horas,...",El equipo de Marcos Dreyer afronta sin bajas u...,El equipo de Marcos Dreyer afronta sin bajas u...,"El Urbia Palma disputa hoy, a las 20:00 horas,..."
1,1,El presidente de la Sociedad de Garantía Recíp...,"El presidente, José Roca, afirma que el ejecut...","El presidente, José Roca, afirma que el ejecut...",El presidente de la Sociedad de Garantía Recíp...
2,2,Agentes de la Policía Nacional han detenido en...,Los detenidos la invitan a su domicilio y la e...,Los detenidos la invitan a su domicilio y la e...,Agentes de la Policía Nacional han detenido en...
3,3,Consumir ibuprofeno sin receta médica aumenta ...,Un estudio realizado en Dinamarca alerta sobre...,Un estudio realizado en Dinamarca alerta sobre...,Consumir ibuprofeno sin receta médica aumenta ...
4,4,"Hay arroces y arroces, pero ¿cuántas veces te ...",Miquel Antoja te enseña paso a paso cómo hacer...,Miquel Antoja te enseña paso a paso cómo hacer...,"Hay arroces y arroces, pero ¿cuántas veces te ..."
...,...,...,...,...,...
42592,42592,Un equipo de investigadores canadienses ha enc...,El camu-camu contiene entre 20 y 30 veces más ...,El camu-camu contiene entre 20 y 30 veces más ...,Un equipo de investigadores canadienses ha enc...
42593,42593,"Belén Canalejo, autora del exitoso blog Balamo...",La autora del exitoso blog Balamoda.net nos of...,La autora del exitoso blog Balamoda.net nos of...,"Belén Canalejo, autora del exitoso blog Balamo..."
42594,42594,"La sociedad Azora cobrará 224,5 millones de eu...",La sociedad gestora pone fin a su contrato con...,La sociedad gestora pone fin a su contrato con...,"La sociedad Azora cobrará 224,5 millones de eu..."
42595,42595,Imagen correspondiente a los bombardeos sobre ...,Los Comités de Coordinación Local aseguran que...,Los Comités de Coordinación Local aseguran que...,Imagen correspondiente a los bombardeos sobre ...
42596,42596,El acuerdo de legislatura que han suscrito PSO...,El acuerdo de legislatura prevé bajar el IVA c...,El acuerdo de legislatura prevé bajar el IVA c...,El acuerdo de legislatura que han suscrito PSO...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42597 entries, 0 to 42596
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  42597 non-null  int64
 1   0           42597 non-null  object
 2   1           42597 non-null  object
dtypes: int64(1), object(2)
memory usage: 998.5+ KB

In [ ]:
df["summary"]=df["1"]

In [ ]:
df["text"]=df["0"]

In [ ]:
df["text"][36153]

'Los partidos del Pacte del Grau –PSPV, Compromís y Castelló en Moviment- han aprobado en el pleno de hoy una moción de censura conjunta para la retirada de todos los símbolos franquistas de la ciudad. Para el Partido Popular, que acusa a los partidos del Pacte de “sectarios y totalitarios”, el monumento -inaugurado en 1939 con el lema “Caídos por Dios y por España”- supone un homenaje a "las víctimas que a lo largo de la historia reciente de nuestro país han pagado con su vida" para conseguir la actual democracia española. El Partido Popular considera, además, que la intención de retirar la cruz es una "maniobra electoral" que rompe los consensos de la transición y es "una nueva muestra de persecución de los símbolos católicos". Desde Ciudadanos coinciden en que la cruz es únicamente un símbolo religioso. Además, declaran que este no es un tema que preocupe a la gente de Castellón y que tiene más que ver con cumplir un “ideario partidista que traslada los complejos de identidad, odios y rencores”. A pesar de que en un principio existían discrepancias sobre qué órgano debía iniciar el procedimiento administrativo y cómo llevarlo a cabo, la portavoz de Compromís, Verónica Ruíz, anunciaba que los partidos del pacto han llegado finalmente a un acuerdo\xa0 y será Cultura –y no a Urbanismo, como en principio defendía Compromís- quien dé comienzo a los procedimientos para retirar la cruz franquista de Ribalta. Desde el grupo socialista han expresado su alegría por el acuerdo obtenido y manifiestan que el añadir la enmienda correspondía a un intento por asegurarse de que se cumplían todas las garantías ya que consideran “la voluntad política no está por encima del resto de factores en la toma de decisiones”. Los partidos del pacto también han destacado los informes del Comité de Expertos, adscritos a la Conselleria de Justicia -que indica el carácter franquista del monumento-, para negar que la cruz suponga únicamente un símbolo religioso. Señalaban, además, que el lugar se utiliza para homenajear el franquismo y la necesidad de hacer cumplir la Ley de Memoria Histórica.'

In [ ]:
df["summary"][36153]

'La moción aprobada plantea, además, la eliminación de todos los símbolos franquistas de la ciudad. Para los colectivos de defensa de la cruz, vinculados al Partido Popular, lo que motiva la retirada de esta cruz es “sólo el odio a todo lo que huele a religión”.'

In [ ]:
import zipfile
with zipfile.ZipFile("./val.zip", 'r') as zip_ref:
    zip_ref.extractall("val")

In [ ]:
import pandas as pd
df1 = pd.read_json("./val/val/text1.json")
df1

,@text,@confidence,@support,@types,@sparql,@policy,Resources
0,El presidente de la Sociedad de Garantía Recíp...,0.75,0,,,whitelist,{'@URI': 'http://es.dbpedia.org/resource/Ponga...
1,El presidente de la Sociedad de Garantía Recíp...,0.75,0,,,whitelist,{'@URI': 'http://es.dbpedia.org/resource/Agenc...
2,El presidente de la Sociedad de Garantía Recíp...,0.75,0,,,whitelist,{'@URI': 'http://es.dbpedia.org/resource/Banco...
3,El presidente de la Sociedad de Garantía Recíp...,0.75,0,,,whitelist,{'@URI': 'http://es.dbpedia.org/resource/Levan...
4,El presidente de la Sociedad de Garantía Recíp...,0.75,0,,,whitelist,{'@URI': 'http://es.dbpedia.org/resource/Banco...
5,El presidente de la Sociedad de Garantía Recíp...,0.75,0,,,whitelist,{'@URI': 'http://es.dbpedia.org/resource/Banco...
6,El presidente de la Sociedad de Garantía Recíp...,0.75,0,,,whitelist,{'@URI': 'http://es.dbpedia.org/resource/Madri...
7,El presidente de la Sociedad de Garantía Recíp...,0.75,0,,,whitelist,{'@URI': 'http://es.dbpedia.org/resource/Banco...

In [ ]:
df1['Resources'][0]

{'@URI': 'http://es.dbpedia.org/resource/Ponga',
 '@support': '131',
 '@types': 'Wikidata:Q3455524,Schema:Place,Schema:AdministrativeArea,DBpedia:Region,DBpedia:PopulatedPlace,DBpedia:Place,DBpedia:Location,DBpedia:GovernmentalAdministrativeRegion,DBpedia:AdministrativeRegion,DBpedia:Municipality',
 '@surfaceForm': 'ponga',
 '@offset': '443',
 '@similarityScore': '0.9999999999997726',
 '@percentageOfSecondRank': '0.0'}

In [ ]:
[[],[]]

In [ ]:
df1['Resources'][1]['@support']

'841'

In [ ]:
df1['Resources'][1]['@surfaceForm']

In [ ]:
df1['Resources'][1]['@types']

'Wikidata:Q43229,Wikidata:Q24229398,DUL:SocialPerson,DUL:Agent,Schema:Organization,DBpedia:Agent,DBpedia:Organisation'

In [ ]:

  def encontrar(df1,j,suport):
    cont=0;
    ofset=0;
    if int(df1['Resources'][j]['@support'])>suport:
      for k in range(0,len(df1['Resources'][j]['@types'])):
        if df1['Resources'][j]['@types'][k] == "S":
          if df1['Resources'][j]['@types'][k+1] == "c":
            if df1['Resources'][j]['@types'][k+2] == "h":
              if df1['Resources'][j]['@types'][k+3] == "e":
                if df1['Resources'][j]['@types'][k+4] == "m":
                  if df1['Resources'][j]['@types'][k+5] == "a":
                    if df1['Resources'][j]['@types'][k+6] == ":":
                      ofset=k+6
                      if df1['Resources'][j]['@types'][k+7] != ",":
                        cont=cont+1
                        if df1['Resources'][j]['@types'][k+8] != ",":
                          cont=cont+1
                          if df1['Resources'][j]['@types'][k+9] != ",":
                            cont=cont+1
                            if df1['Resources'][j]['@types'][k+10] != ",":
                              cont=cont+1
                              if df1['Resources'][j]['@types'][k+11] != ",":
                                cont=cont+1
                                if df1['Resources'][j]['@types'][k+12] != ",":
                                  cont=cont+1
                                  if df1['Resources'][j]['@types'][k+13] != ",":
                                    cont=cont+1
                                    if df1['Resources'][j]['@types'][k+14] != ",":
                                      cont=cont+1
                                      if df1['Resources'][j]['@types'][k+15] != ",":
                                        cont=cont+1
                                        if df1['Resources'][j]['@types'][k+16] != ",":
                                          cont=cont+1
                                          if df1['Resources'][j]['@types'][k+17] != ",":
                                            cont=cont+1
                                            if df1['Resources'][j]['@types'][k+18] != ",":
                                              cont=cont+1
                                              if df1['Resources'][j]['@types'][k+19] != ",":
                                                  cont=cont+1
                                                  if df1['Resources'][j]['@types'][k+20] != ",":
                                                    cont=cont+1
                                                    if df1['Resources'][j]['@types'][k+21] != ",":
                                                      cont=cont+1
                                                      if df1['Resources'][j]['@types'][k+22] != ",":
                                                        cont=cont+1
                                                        if df1['Resources'][j]['@types'][k+23] != ",":
                                                          cont=cont+1
                                                          if df1['Resources'][j]['@types'][k+24] != ",":
                                                            cont=cont+1
                                                            if df1['Resources'][j]['@types'][k+25] != ",":
                                                              cont=cont+1
                                                              if df1['Resources'][j]['@types'][k+26] != ",":
                                                                cont=cont+1
                                                                if df1['Resources'][j]['@types'][k+27] != ",":
                                                                  cont=cont+1
                                                                  if df1['Resources'][j]['@types'][k+28] != ",":
                                                                    cont=cont+1
                                                                    if df1['Resources'][j]['@types'][k+29] != ",":
                                                                      cont=cont+1
                                                                      if df1['Resources'][j]['@types'][k+30] != ",":
                                                                        cont=cont+1
                                                                        if df1['Resources'][j]['@types'][k+31] != ",":
                                                                            cont=cont+1
                                                                        else:
                                                                          return (cont,ofset)
                                                                      else:
                                                                        return (cont,ofset)
                                                                    else:
                                                                      return (cont,ofset)
                                                                  else:
                                                                    return (cont,ofset)
                                                                else:
                                                                  return (cont,ofset)
                                                              else:
                                                                return (cont,ofset)
                                                            else:
                                                              return (cont,ofset)
                                                          else:
                                                            return (cont,ofset)
                                                        else:
                                                          return (cont,ofset)
                                                      else:
                                                        return (cont,ofset)
                                                    else:
                                                      return (cont,ofset)
                                                  else:
                                                    return (cont,ofset)
                                              else:
                                                return (cont,ofset)
                                            else:
                                              return (cont,ofset)
                                          else:
                                            return (cont,ofset)
                                        else:
                                          return (cont,ofset)
                                      else:
                                        return (cont,ofset)
                                    else:
                                      return (cont,ofset)
                                  else:
                                    return (cont,ofset)
                                else:
                                  return (cont,ofset)
                              else:
                                return (cont,ofset)
                            else:
                              return (cont,ofset)
                          else:
                            return (cont,ofset)
                        else:
                          return (cont,ofset)
                      else:
                        return (cont,ofset)


    return 0

In [ ]:
  resultado=[]
  for j in range(0,len(df1['Resources'])):
    a=encontrar(df1,j,700)
    if len(str(a))>1:
      b=a[1]
      c=a[1]+a[0]
      resultado.append(df1['Resources'][j]['@types'][b+1:c+1])
    else:
      resultado.append(0)
  resultado

NameError: ignored

In [ ]:

for j in range(0,len(df1['Resources'])):
  print(df1['Resources'][j]['@support'])

131
841
1489
423
1489
1489
164364
1489

8

In [ ]:
len(resultado)

8

In [ ]:
errores=0
final=[]
for l in range(0,42597):
  try:
    df2 = pd.read_json("./val/val/text"+str(l)+".json")
    resultadoM=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j,700)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append(df2['Resources'][j]['@types'][b+1:c+1])
    for w in resultadoM:
      if final.count(w)==0:
        final.append(w)
  except:
    errores=errores+1
errores

In [ ]:
for l in range(0,42597):
  try:
    df2 = pd.read_json("./val/val/text"+str(l)+".json")
    resultadoM=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append(df2['Resources'][j]['@types'][b+1:c+1])
    for w in resultadoM:
      if final.count(w)==0:
        final.append(w)
  except:
    loko="error en: text"+str(l)+".json"
    print(loko)

In [ ]:
final

['SportsEvent',
 'Place',
 'Organization',
 'WebSite',
 'Movie',
 'CreativeWork',
 'Person',
 'StadiumOrArena',
 'Event',
 'TelevisionStation',
 'RadioStation',
 'SportsTeam',
 'Language',
 'Product',
 'Airport',
 'RiverBodyOfWater']

In [ ]:
df2 = pd.read_json("./val/val/text1.json")

In [ ]:
import pandas as pd

In [ ]:
errores=0
final=[]
for l in range(0,42597):
  try:
    df2 = pd.read_json("./val/val/text"+str(l)+".json")
    resultadoM=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j,400)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append(df2['Resources'][j]['@types'][b+1:c+1])
    for w in resultadoM:
      if final.count(w)==0:
        final.append(w)
  except:
    errores=errores+1
errores

176

In [ ]:
final

['SportsEvent',
 'Place',
 'Organization',
 'CreativeWork',
 'WebSite',
 'Movie',
 'Person',
 'StadiumOrArena',
 'Event',
 'TelevisionStation',
 'RadioStation',
 'SportsTeam',
 'Language',
 'Product',
 'Airport',
 'MusicAlbum',
 'Painting',
 'RiverBodyOfWater']

In [ ]:
errores=0
final=[]
for l in range(0,42597):
  try:
    df2 = pd.read_json("./val/val/text"+str(l)+".json")
    resultadoM=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j,200)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append(df2['Resources'][j]['@types'][b+1:c+1])
    for w in resultadoM:
      if final.count(w)==0:
        final.append(w)
  except:
    errores=errores+1
errores

176

In [ ]:
final

['SportsTeam',
 'SportsEvent',
 'Place',
 'Organization',
 'CreativeWork',
 'WebSite',
 'Movie',
 'Person',
 'StadiumOrArena',
 'Event',
 'TelevisionStation',
 'RadioStation',
 'Language',
 'Product',
 'Airport',
 'School',
 'MusicAlbum',
 'RiverBodyOfWater',
 'Painting',
 'TVEpisode']

In [ ]:
errores=0

for l in range(0,718113):
  try:
    df2 = pd.read_json("./train/train/text"+str(l)+".json")
    resultadoM=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j,400)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append(df2['Resources'][j]['@types'][b+1:c+1])
    for w in resultadoM:
      if final.count(w)==0:
        final.append(w)
  except:
    errores=errores+1
errores

3302

In [ ]:
final

['SportsTeam',
 'SportsEvent',
 'Place',
 'Organization',
 'CreativeWork',
 'WebSite',
 'Movie',
 'Person',
 'StadiumOrArena',
 'Event',
 'TelevisionStation',
 'RadioStation',
 'Language',
 'Product',
 'Airport',
 'School',
 'MusicAlbum',
 'RiverBodyOfWater',
 'Painting',
 'TVEpisode']

['SportsTeam', ----> equipo deportivo
 'SportsEvent', ----> evento deportivo
 'Place',  -----> lugar
 'Organization',  -----> organización
 'CreativeWork',  ------> trabajo creativo
 'WebSite',  ------> página web
 'Movie',  ------> película
 'Person',  -----> persona
 'StadiumOrArena', ------> estadio
 'Event',  ------> evento
 'TelevisionStation', ------> canal de televisión
 'RadioStation', ----> canal de radio
 'Language', ------> idioma
 'Product', ------> producto
 'Airport', ------> aeropuerto
 'School', ------> colegio
 'MusicAlbum', ------> disco de música
 'RiverBodyOfWater', ------> río
 'Painting', ------> cuadro
 'TVEpisode'] ------> episodio de televisión

In [ ]:
  import pandas as pd
  df = pd.read_csv('./700tokensVal.csv', sep=";")
  df["summary"]=df["1"]
  df["article"]=df["0"]
  df.dropna()

,Unnamed: 0,0,1,summary,article
0,0,"El Urbia Palma disputa hoy, a las 20:00 horas,...",El equipo de Marcos Dreyer afronta sin bajas u...,El equipo de Marcos Dreyer afronta sin bajas u...,"El Urbia Palma disputa hoy, a las 20:00 horas,..."
1,1,El presidente de la Sociedad de Garantía Recíp...,"El presidente, José Roca, afirma que el ejecut...","El presidente, José Roca, afirma que el ejecut...",El presidente de la Sociedad de Garantía Recíp...
2,2,Agentes de la Policía Nacional han detenido en...,Los detenidos la invitan a su domicilio y la e...,Los detenidos la invitan a su domicilio y la e...,Agentes de la Policía Nacional han detenido en...
3,3,Consumir ibuprofeno sin receta médica aumenta ...,Un estudio realizado en Dinamarca alerta sobre...,Un estudio realizado en Dinamarca alerta sobre...,Consumir ibuprofeno sin receta médica aumenta ...
4,4,"Hay arroces y arroces, pero ¿cuántas veces te ...",Miquel Antoja te enseña paso a paso cómo hacer...,Miquel Antoja te enseña paso a paso cómo hacer...,"Hay arroces y arroces, pero ¿cuántas veces te ..."
...,...,...,...,...,...
42592,42592,Un equipo de investigadores canadienses ha enc...,El camu-camu contiene entre 20 y 30 veces más ...,El camu-camu contiene entre 20 y 30 veces más ...,Un equipo de investigadores canadienses ha enc...
42593,42593,"Belén Canalejo, autora del exitoso blog Balamo...",La autora del exitoso blog Balamoda.net nos of...,La autora del exitoso blog Balamoda.net nos of...,"Belén Canalejo, autora del exitoso blog Balamo..."
42594,42594,"La sociedad Azora cobrará 224,5 millones de eu...",La sociedad gestora pone fin a su contrato con...,La sociedad gestora pone fin a su contrato con...,"La sociedad Azora cobrará 224,5 millones de eu..."
42595,42595,Imagen correspondiente a los bombardeos sobre ...,Los Comités de Coordinación Local aseguran que...,Los Comités de Coordinación Local aseguran que...,Imagen correspondiente a los bombardeos sobre ...
42596,42596,El acuerdo de legislatura que han suscrito PSO...,El acuerdo de legislatura prevé bajar el IVA c...,El acuerdo de legislatura prevé bajar el IVA c...,El acuerdo de legislatura que han suscrito PSO...

In [ ]:
def reemplazar(strr):
  strr=str(strr)
  strr=strr.replace('SportsTeam',"equipo deportivo")
  strr=strr.replace('SportsEvent',"evento deportivo")
  strr=strr.replace('Place', "lugar")
  strr=strr.replace('Organization',"organización")
  strr=strr.replace('CreativeWork',"trabajo creativo")
  strr=strr.replace('WebSite',"página web")
  strr=strr.replace('Movie',"película")
  strr=strr.replace('Person',"persona")
  strr=strr.replace('StadiumOrArena',"estadio")
  strr=strr.replace('Event',"evento")
  strr=strr.replace('TelevisionStation',"canal de televisión")
  strr=strr.replace('RadioStation',"canal de radio")
  strr=strr.replace('Language'," idioma")
  strr=strr.replace('Product',"producto")
  strr=strr.replace('Airport',"aeropuerto")
  strr=strr.replace('School',"colegio")
  strr=strr.replace('MusicAlbum',"disco de música")
  strr=strr.replace('RiverBodyOfWater'," río")
  strr=strr.replace('Painting',"cuadro")
  strr=strr.replace('TVEpisode',"episodio de televisión")
  return strr

In [ ]:
errores=0

for l in range(0,718113):
  try:
    df2 = pd.read_json("./train/train/text"+str(l)+".json")
    resultadoM=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j,400)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append(df2['Resources'][j]['@types'][b+1:c+1])
    for w in resultadoM:
      if final.count(w)==0:
        final.append(w)
  except:
    errores=errores+1
errores

In [ ]:
errores=0
resultadooo=[]
for l in range(0,42597):
  try:
    df2 = pd.read_json("./val/val/text"+str(l)+".json")
    resultadoM=[]
    final=[]
    final2=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j,200)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append((df2['Resources'][j]['@types'][b+1:c+1],df2['Resources'][j]['@surfaceForm']))
        #print(resultadoM)
    texto=str(df["article"][l])
    texto="Texto:{ " + texto + " }" + "Entidades: { "
    for y in range(0,len(resultadoM)):
      #print(resultadoM[y])
      if final.count(resultadoM[y][1])==0:
        final.append(resultadoM[y][1])
        final2.append(resultadoM[y][0])
    #print(final)
    for x in range(0,len(final)):
      texto = texto + str(final[x]) + " es " + reemplazar(str(final2[x])) + ", "
    texto = texto + "}"
    resultadooo.append(texto)
  except Exception as e:
    texto=str(df["article"][l])
    errores=errores+1
    texto="Texto:{ " + texto + " }" + "Entidades: {}"
    resultadooo.append(texto)
    print(e)
errores

In [ ]:
resultadooo[0]

'Texto:{ El Urbia Palma disputa hoy, a las 20:00 horas, la cuarta jornada de la Superliga Masculina frente al Melilla en el pabellón Javier Imbroda. Los de Marcos Dreyer buscarán alargar su pleno de victorias en una complicada pista antes de la cita del próximo miércoles en la Supercopa de España en Teruel. El conjunto mallorquín viajó ayer, sin ninguna baja en sus filas, hasta la ciudad norteafricana realizando escalas previas en Madrid y Málaga. Además del largo desplazamiento, Dreyer considera clave "la adaptación al pabellón en acciones tan importantes como el saque y la recepción". Los melillenses arrancaron con derrota en la pista del Unicaja Almería (3-0) y en la segunda jornada lograron su primer triunfo como local ante L\'Illa Grau (3-0). En el último encuentro vendieron cara su derrota ante el Vecindario, apurando hasta el quinto set. Por ello que el entrenador del Urbia advirtió de que el grupo de David Sánchez Flor "también aspira a estar arriba y puede llegar a ser un rival directo". "Jugando en casa saldrán a por todas", añadió. Tras imponerse a Ushuaïa Eivissa, Textil Santanderina y Barcelona, continúa el reto de seguir imbatido para el vigente campeón de Liga. Además, los otros equipos aún invictos, Unicaja Almería y Teruel, juegan este fin de semana ante Soria y Barça respectivamente. En este sentido, el técnico brasileño recalca que "esta jornada podría definirse el liderato", sin esconder que "siempre está bien verse en la parte alta". "Queremos afianzar nuestra confianza de cara a la Supercopa. Más allá del resultado en Melilla queremos llegar con buenas sensaciones en el juego", indicó Dreyer con respecto al duelo de este miércoles por el primer título de la temporada, frente el Teruel. }Entidades: { Melilla es equipo deportivo, Supercopa es evento deportivo, España es lugar, Teruel es lugar, Madrid es lugar, Málaga es lugar, Almería es lugar, Barcelona es organización, Liga es organización, Soria es lugar, }'

In [ ]:
pd4=pd.DataFrame(resultadooo,df["summary"])
pd4

                                                                                                    0
summary
El equipo de Marcos Dreyer afronta sin bajas un...  Texto:{ El Urbia Palma disputa hoy, a las 20:0...
El presidente, José Roca, afirma que el ejecuti...  Texto:{ El presidente de la Sociedad de Garant...
Los detenidos la invitan a su domicilio y la en...  Texto:{ Agentes de la Policía Nacional han det...
Un estudio realizado en Dinamarca alerta sobre ...  Texto:{ Consumir ibuprofeno sin receta médica ...
Miquel Antoja te enseña paso a paso cómo hacerl...  Texto:{ Hay arroces y arroces, pero ¿cuántas v...
...                                                                                               ...
El camu-camu contiene entre 20 y 30 veces más v...  Texto:{ Un equipo de investigadores canadiense...
La autora del exitoso blog Balamoda.net nos ofr...  Texto:{ Belén Canalejo, autora del exitoso blo...
La sociedad gestora pone fin a su contrato con ...  Texto:{ La sociedad Azora cobrará 224,5 millon...
Los Comités de Coordinación Local aseguran que ...  Texto:{ Imagen correspondiente a los bombardeo...
El acuerdo de legislatura prevé bajar el IVA cu...  Texto:{ El acuerdo de legislatura que han susc...

[42597 rows x 1 columns]

In [ ]:
pd4.to_csv("700tokensTrainEnt.csv", sep=';')

In [ ]:
import shutil

# Copia el archivo desde el drive al entorno de ejecucion

shutil.copyfile("./drive/MyDrive/data/700tokens.csv","./700tokens.csv")

'./700tokens.csv'

In [ ]:
import pandas as pd
df = pd.read_csv("700tokens.csv", sep=";")
df["summary"]=df["1"]
df["article"]=df["0"]

In [ ]:
errores=0
resultadooo=[]
for l in range(0,718113):
  try:
    df2 = pd.read_json("./train/train/text"+str(l)+".json")
    resultadoM=[]
    final=[]
    final2=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j,200)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append((df2['Resources'][j]['@types'][b+1:c+1],df2['Resources'][j]['@surfaceForm']))
        #print(resultadoM)
    texto=str(df["article"][l])
    texto="Texto:{ " + texto + " }" + "Entidades: { "
    for y in range(0,len(resultadoM)):
      #print(resultadoM[y])
      if final.count(resultadoM[y][1])==0:
        final.append(resultadoM[y][1])
        final2.append(resultadoM[y][0])
    #print(final)
    for x in range(0,len(final)):
      texto = texto + str(final[x]) + " es " + reemplazar(str(final2[x])) + ", "
    texto = texto + "}"
    resultadooo.append(texto)
  except Exception as e:
    texto=str(df["article"][l])
    errores=errores+1
    texto="Texto:{ " + texto + " }" + "Entidades: {}"
    resultadooo.append(texto)
    print(e)
errores

In [ ]:
pd5=pd.DataFrame(resultadooo,df["summary"])
pd5

                                                                                                    0
summary
La mujer, de 28 años, tiene quemaduras graves y...  Texto:{ La madre de 28 años grave por quemadur...
Hay que quedarse con la interpretación de Fanny...  Texto:{ LOLA PATE. Dirección: Nadir Moknèche. ...
El cuerpo en juego. Microsoft muestra su sistem...  Texto:{ Una cámara especial es el único comple...
El Instituto Andaluz de la Mujer le abrió un ex...  Texto:{ El empresario onubense que buscaba, a ...
Nadar como un delfín, volar hasta doce metros d...  Texto:{ Unas botas, una tabla y el agua del ma...
...                                                                                               ...
El juez libera al joven, que no ha querido decl...  Texto:{ El juez ha dejado en libertad al joven...
Los trajes que lucirán en la proclamación y los...  Texto:{ Oro viejo y verde mar. Estos son los c...
Montilla Acatamos, pero no compartimos ni renun...  Texto:{ El presidente de la Generalitat, José ...
La Iglesia aplica el nuevo procedimiento breve ...  Texto:{ El arzobispo de Sevilla, Juan José Ase...
El Prepara prevé una ayuda de entre 400 y 450 e...  Texto:{ La ministra de Empleo, Fátima Báñez, h...

[718113 rows x 1 columns]

In [ ]:
pd5.to_csv("700tokensTrainEnti.csv", sep=';')

In [ ]:
import pandas as pd
df = pd.read_csv("700tokensTrainEnti.csv", sep=";")
df

,summary,0
0,"La mujer, de 28 años, tiene quemaduras graves ...",Texto:{ La madre de 28 años grave por quemadur...
1,Hay que quedarse con la interpretación de Fann...,Texto:{ LOLA PATE. Dirección: Nadir Moknèche. ...
2,El cuerpo en juego. Microsoft muestra su siste...,Texto:{ Una cámara especial es el único comple...
3,El Instituto Andaluz de la Mujer le abrió un e...,"Texto:{ El empresario onubense que buscaba, a ..."
4,"Nadar como un delfín, volar hasta doce metros ...","Texto:{ Unas botas, una tabla y el agua del ma..."
...,...,...
718108,"El juez libera al joven, que no ha querido dec...",Texto:{ El juez ha dejado en libertad al joven...
718109,Los trajes que lucirán en la proclamación y lo...,Texto:{ Oro viejo y verde mar. Estos son los c...
718110,"Montilla Acatamos, pero no compartimos ni renu...","Texto:{ El presidente de la Generalitat, José ..."
718111,La Iglesia aplica el nuevo procedimiento breve...,"Texto:{ El arzobispo de Sevilla, Juan José Ase..."
718112,El Prepara prevé una ayuda de entre 400 y 450 ...,"Texto:{ La ministra de Empleo, Fátima Báñez, h..."

In [ ]:
import pandas as pd
df = pd.read_csv("700tokensValEnt.csv", sep=";")
df["article"]=df["0"]

In [ ]:
df

,summary,0,article
0,El equipo de Marcos Dreyer afronta sin bajas u...,"Texto:{ El Urbia Palma disputa hoy, a las 20:0...","Texto:{ El Urbia Palma disputa hoy, a las 20:0..."
1,"El presidente, José Roca, afirma que el ejecut...",Texto:{ El presidente de la Sociedad de Garant...,Texto:{ El presidente de la Sociedad de Garant...
2,Los detenidos la invitan a su domicilio y la e...,Texto:{ Agentes de la Policía Nacional han det...,Texto:{ Agentes de la Policía Nacional han det...
3,Un estudio realizado en Dinamarca alerta sobre...,Texto:{ Consumir ibuprofeno sin receta médica ...,Texto:{ Consumir ibuprofeno sin receta médica ...
4,Miquel Antoja te enseña paso a paso cómo hacer...,"Texto:{ Hay arroces y arroces, pero ¿cuántas v...","Texto:{ Hay arroces y arroces, pero ¿cuántas v..."
...,...,...,...
42592,El camu-camu contiene entre 20 y 30 veces más ...,Texto:{ Un equipo de investigadores canadiense...,Texto:{ Un equipo de investigadores canadiense...
42593,La autora del exitoso blog Balamoda.net nos of...,"Texto:{ Belén Canalejo, autora del exitoso blo...","Texto:{ Belén Canalejo, autora del exitoso blo..."
42594,La sociedad gestora pone fin a su contrato con...,"Texto:{ La sociedad Azora cobrará 224,5 millon...","Texto:{ La sociedad Azora cobrará 224,5 millon..."
42595,Los Comités de Coordinación Local aseguran que...,Texto:{ Imagen correspondiente a los bombardeo...,Texto:{ Imagen correspondiente a los bombardeo...
42596,El acuerdo de legislatura prevé bajar el IVA c...,Texto:{ El acuerdo de legislatura que han susc...,Texto:{ El acuerdo de legislatura que han susc...

In [ ]:
import zipfile
with zipfile.ZipFile("./test.zip", 'r') as zip_ref:
    zip_ref.extractall("test")

In [ ]:
import pandas as pd
df = pd.read_csv("700tokensTest-i.csv", sep=";")
df["summary"]=df["1"]
df["article"]=df["0"]

In [ ]:
df

,Unnamed: 0,0,1,summary,article
0,0,"La presidenta de Baleares, Francina Armengol, ...",Armengol ha señalado que 'en todo momento' ha ...,Armengol ha señalado que 'en todo momento' ha ...,"La presidenta de Baleares, Francina Armengol, ..."
1,1,El amor de Mar Flores y Elías Sacal se ha term...,La modelo y el empresario mexicano han decidid...,La modelo y el empresario mexicano han decidid...,El amor de Mar Flores y Elías Sacal se ha term...
2,2,El Ibex 35 ha cerrado la sesión de este lunes ...,"El índice de la Bolsa se deja un 1,44% al cier...","El índice de la Bolsa se deja un 1,44% al cier...",El Ibex 35 ha cerrado la sesión de este lunes ...
3,3,Más de 40 millones de personas han visitado el...,El canal de Youtube del Animal Adventure Park ...,El canal de Youtube del Animal Adventure Park ...,Más de 40 millones de personas han visitado el...
4,4,La comisión francesa de investigación del sini...,Comienza el proceso de reparación del sistema ...,Comienza el proceso de reparación del sistema ...,La comisión francesa de investigación del sini...
...,...,...,...,...,...
42554,42554,El Rey Juan Carlos celebra hoy su 73 cumpleaño...,El monarca lo festejará con una celebración fa...,El monarca lo festejará con una celebración fa...,El Rey Juan Carlos celebra hoy su 73 cumpleaño...
42555,42555,"El grupo de investigación de Esadib, la Escola...",La muestra recoge el trabajo de fin de curso d...,La muestra recoge el trabajo de fin de curso d...,"El grupo de investigación de Esadib, la Escola..."
42556,42556,La capital de Baleares se convertirá en el cen...,La capital de Baleares se convertirá en el cen...,La capital de Baleares se convertirá en el cen...,La capital de Baleares se convertirá en el cen...
42557,42557,El Hospital ha puesto en marcha un programa de...,Los pacientes desarrollan dinámicas personales...,Los pacientes desarrollan dinámicas personales...,El Hospital ha puesto en marcha un programa de...
42558,42558,"El Hospital La Fe de Valencia ya está ""autoriz...",Sanidad anunció que el hospital que haga los p...,Sanidad anunció que el hospital que haga los p...,"El Hospital La Fe de Valencia ya está ""autoriz..."

In [ ]:
errores=0
resultadooo=[]
for l in range(0,42559):
  try:
    df2 = pd.read_json("./test/test/text"+str(l)+".json")
    resultadoM=[]
    final=[]
    final2=[]
    for j in range(0,len(df2['Resources'])):
      a=encontrar(df2,j,200)
      if len(str(a))>1:
        b=a[1]
        c=a[1]+a[0]
        resultadoM.append((df2['Resources'][j]['@types'][b+1:c+1],df2['Resources'][j]['@surfaceForm']))
        #print(resultadoM)
    texto=str(df["article"][l])
    texto="Texto:{ " + texto + " }" + "Entidades: { "
    for y in range(0,len(resultadoM)):
      #print(resultadoM[y])
      if final.count(resultadoM[y][1])==0:
        final.append(resultadoM[y][1])
        final2.append(resultadoM[y][0])
    #print(final)
    for x in range(0,len(final)):
      texto = texto + str(final[x]) + " es " + reemplazar(str(final2[x])) + ", "
    texto = texto + "}"
    resultadooo.append(texto)
  except Exception as e:
    texto=str(df["article"][l])
    errores=errores+1
    texto="Texto:{ " + texto + " }" + "Entidades: {}"
    resultadooo.append(texto)
    print(e)
errores

If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index
If using all scalar values, you must pass an index

170

In [ ]:
pd5=pd.DataFrame(resultadooo,df["summary"])
pd5

                                                                                                    0
summary
Armengol ha señalado que 'en todo momento' ha h...  Texto:{ La presidenta de Baleares, Francina Ar...
La modelo y el empresario mexicano han decidido...  Texto:{ El amor de Mar Flores y Elías Sacal se...
El índice de la Bolsa se deja un 1,44% al cierr...  Texto:{ El Ibex 35 ha cerrado la sesión de est...
El canal de Youtube del Animal Adventure Park d...  Texto:{ Más de 40 millones de personas han vis...
Comienza el proceso de reparación del sistema e...  Texto:{ La comisión francesa de investigación ...
...                                                                                               ...
El monarca lo festejará con una celebración fam...  Texto:{ El Rey Juan Carlos celebra hoy su 73 c...
La muestra recoge el trabajo de fin de curso de...  Texto:{ El grupo de investigación de Esadib, l...
La capital de Baleares se convertirá en el cent...  Texto:{ La capital de Baleares se convertirá e...
Los pacientes desarrollan dinámicas personales ...  Texto:{ El Hospital ha puesto en marcha un pro...
Sanidad anunció que el hospital que haga los pr...  Texto:{ El Hospital La Fe de Valencia ya está ...

[42559 rows x 1 columns]

In [ ]:
pd5.to_csv("700tokensTestiEnt.csv", sep=';')